name: Test Workflow
on: push

jobs:
  first-workflow:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: npm clean install
        run: |
          npm install