name: Test Workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  first-workflow:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run npm ci
        run: npm ci
      - name: Run npm test
        run: npm test
      - name: npm install
        run: |
          npm install